# Array in Python

- In array all values are of same type
- ## Advantage: 
- Arrays in python don't have specific size(Dynamic Array), means we can expand/shrink.
- Methods: .append, .find, .index etc.

- To us array need to import --->    **import array**

<img src = "image/array_type.png" align="left" style="width:500px; height:300px"/>

In [1]:
import array as arr   # this requires calling function as arr.___()

from array import *  #to avoid writing code as arr.___, we can directly call funcion by importing all the required function 

In [2]:
#1. specify type, but we have to use type code not the keywords
#2. Mention values

vals = array('i', [5,9,8,4,2])      
print(vals)
type(vals)

array('i', [5, 9, 8, 4, 2])


array.array

In [3]:
print(vals.buffer_info())              #gives( address, size) of array

(2151974287152, 5)


In [4]:
vals.reverse()
print(vals)

array('i', [2, 4, 8, 9, 5])


## Array using For Loop

In [5]:
for i in range(5):
    print(vals[i], end = " ")

2 4 8 9 5 

In [6]:
for i in range(len(vals)):
    print(vals[i], end = " ")

2 4 8 9 5 

In [7]:
for i in vals:
    print(i, end = " ")

2 4 8 9 5 

In [8]:
newArr = array(vals.typecode,(a for a in vals))   # creating new array with same values
                                                  # since copying from the previous array, we can copy the type of array.....
for i in newArr:                                  # using .typecode method
    print(i, end = " ")                           # using for loop we can assign values from previous array to new array.

2 4 8 9 5 

In [9]:
newArr2 = array(vals.typecode,(a*a for a in vals))                                                    
for i in newArr2:                                 
    print(i, end = " ") 

4 16 64 81 25 

## Array using while Loop

- **while loop require initialization, condition and the increment/decrement**

In [10]:
newArr3 = array(vals.typecode,(a*a for a in vals))   
i = 0
while i <len(newArr3):
    print(newArr3[i], end = " ")
    i+=1

4 16 64 81 25 

## Array Values from user in python

- Since we will take values from user, we dont know the size of the array, so how to create array ?

In [11]:
arr = array('i',[])                                   # creating empty array
n = int(input("Enter the length of array: "))

for i in range(n):
    x = int(input('Enter the next value: '))
    arr.append(x)
print(arr)

Enter the length of array: 5
Enter the next value: 5
Enter the next value: 10
Enter the next value: 15
Enter the next value: 20
Enter the next value: 25
array('i', [5, 10, 15, 20, 25])


In [12]:
val = int(input("Enter the value for search: "))

k=0
for e in arr:                                                  #e = element
    if e == val:
        print('Required Index value is ',k)
        break
    k+=1 

Enter the value for search: 20
Required Index value is  3


In [13]:
val = int(input("Enter the value for search: "))
print('Required Index value is ',arr.index(val))

Enter the value for search: 15
Required Index value is  2


# Accessing Array Elements

<img src = "image/Access_Arr.png" align="left" style="width:600px; height:450px"/>

In [14]:
import array as arr
a = arr.array('i',[1,2,3,4,5,6])
a

array('i', [1, 2, 3, 4, 5, 6])

In [15]:
a[2]        #accessing value at 2nd index position

3

# Basic Array Operations

- Finding the length of an array
- Adding/Changing element of an array
- Removing/Deleting elements of an array
- Array Concatenation
- Slicing
- Looping through an Array

### 1. Finding length of an array 
- Length of an array is the number of elements that are actually present in an array.
- You can make use of len() function to achieve this.
- The len() function returns an integer value that is equal to the number of elements present in that array.


In [16]:
len(a)

6

### 2. Adding Elements to an Array

1. append() - Add element at the end of an array
2. extend() - Add more than 1 element at the end of an array
3. insert() - Add element at specific position in an array

In [17]:
a = arr.array('d', [1.1, 2.1, 3.1])
a.append(3.4)
print("Array a=",a)

b = arr.array('d',[2.1,3.2,4.6])
b.extend([4.5,3.6,7.2])
print("Array b=",b)

c = arr.array( 'd' , [1.1 , 2.1 ,3.1] )
c.insert(2,3.4)
print("Array c=",c)

Array a= array('d', [1.1, 2.1, 3.1, 3.4])
Array b= array('d', [2.1, 3.2, 4.6, 4.5, 3.6, 7.2])
Array c= array('d', [1.1, 2.1, 3.4, 3.1])


### 2. Removing Elements to an Array

- pop() : remove element and **return it**
- remove() : remove an element with a specific value **without returning it.**

In [18]:
a = arr.array('d', [1.1, 2.1, 3.1,4.5,7,8.2,9,4.6,12,11,2])

In [19]:
a.pop()         #will return value 

2.0

In [20]:
a.pop(-2)

12.0

In [21]:
a

array('d', [1.1, 2.1, 3.1, 4.5, 7.0, 8.2, 9.0, 4.6, 11.0])

In [22]:
a.remove(7.0)     #will not return anything

In [23]:
a

array('d', [1.1, 2.1, 3.1, 4.5, 8.2, 9.0, 4.6, 11.0])

In [24]:
a = arr.array('d', [1.1, 2.2, 3.8, 3.1, 3.7])

print('Popping last element',a.pop())
print('Popping 4th element', a.pop(3))

a.remove(1.1)
print(a)        

Popping last element 3.7
Popping 4th element 3.1
array('d', [2.2, 3.8])


# Array Concatenation

In [25]:
import array as arr

a=arr.array('d',[1.1 , 2.1 ,3.1,2.6,7.8])
b=arr.array('d',[3.7,8.6])
c=arr.array('d')
c=a+b

print("Array c = ",c)

Array c =  array('d', [1.1, 2.1, 3.1, 2.6, 7.8, 3.7, 8.6])


# Slicing an Array:

- An array can be sliced using the **`:`** symbol. This returns a range of elements that we have specified by the index numbers.

In [26]:
a=arr.array('d',[1.1,2.1 ,3.1,2.6,7.8,10,6,5.5,2.3])
a[0:3]

array('d', [1.1, 2.1, 3.1])

In [27]:
a[::-2]

array('d', [2.3, 6.0, 7.8, 3.1, 1.1])

# Looping through an array
1. **for loop**   : iterates over the items of an array specified number of times
2. **while loop** : iterates over the elements until a certain condition is met

In [28]:
a = arr.array('d',[1.1,2.2,3.4,5.6,6.8,7.1,8.3,9.4,9.9])
print("All Values")
for x in a:
    print(x, end = " ")

All Values
1.1 2.2 3.4 5.6 6.8 7.1 8.3 9.4 9.9 

In [29]:
a = arr.array('d',[1.1,2.2,3.4,5.6,6.8,7.1,8.3,9.4,9.9])

b=0
while b<len(a):
    print(a[b], end = " ")
    b=b+1

1.1 2.2 3.4 5.6 6.8 7.1 8.3 9.4 9.9 

In [30]:
b=0
while b<a[2]:
    print(a[b], end = " ")
    b=b+1

1.1 2.2 3.4 5.6 

# Numpy in python

- since array only work for 1D array not helpful in working with multidimensional array
- To work with multidimensional array
> e.g 2D array - Matrix/Vector

- No need to mention type for values in numpy arrays, its optional to mention

In [31]:
import numpy as np

from numpy import *
arr = array([1,2,9,5,6])
arr

array([1, 2, 9, 5, 6])

In [32]:
arr1 = array([1,2,9,5,6], int)
arr1

array([1, 2, 9, 5, 6])

# Different ways of creatig a Numpy array

- array()
- linspace()
- logspace()
- arange()
- zeros()
- ones()

#### array()

In [33]:
arr = array([1,2,3,4,5,6])              #no need to specify type
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int32


In [34]:
arr = array([1,2,3,4,5.3,6.1])              #no need to specify type, its optional
print(arr)                                  #In numpy arrays all arrays converted into float 
print(arr.dtype)

[1.  2.  3.  4.  5.3 6.1]
float64


In [35]:
arr = array([1,2,3,4,5.3,6.1], int)    #If we specify type than it will o/p with all integer value even it contain float value 
print(arr)                             #In numpy arrays all arrays converted into float 
print(arr.dtype)

[1 2 3 4 5 6]
int32


#### linspace()

In [36]:
arr = linspace(0,15,24)              #{start, stop, no of parts} ; 
print(arr)                           #stop (included) , step - No. of parts reqd. to move (break range into reqd step) 
print(arr.dtype)

[ 0.          0.65217391  1.30434783  1.95652174  2.60869565  3.26086957
  3.91304348  4.56521739  5.2173913   5.86956522  6.52173913  7.17391304
  7.82608696  8.47826087  9.13043478  9.7826087  10.43478261 11.08695652
 11.73913043 12.39130435 13.04347826 13.69565217 14.34782609 15.        ]
float64


#### arange()

In [37]:
arr = arange(2,20,2)                #start,stop, step(difference)
print(arr)
print(arr.dtype)

[ 2  4  6  8 10 12 14 16 18]
int32


#### logspace()

In [38]:
arr = logspace(1,40,5)              # start : 10^1, Stop 10^40, no of parts = 5
print(arr)
print(arr.dtype)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
float64


In [39]:
print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


#### Zeros and Ones

In [40]:
arr = zeros(5)              #no need to specify type
print(arr)
print(arr.dtype)

arr = zeros(5, int)              #no need to specify type
print(arr)
print(arr.dtype)

[0. 0. 0. 0. 0.]
float64
[0 0 0 0 0]
int32


In [41]:
arr = ones(5)              #no need to specify type
print(arr)
print(arr.dtype)

arr = ones(5, int)              #no need to specify type
print(arr)
print(arr.dtype)

[1. 1. 1. 1. 1.]
float64
[1 1 1 1 1]
int32


## Copying an array in python

- Array addition
- Aliasing
- Shallow Copy
- Deep Copy`

## Vectorized Operation

In [42]:
#adding value in the existing array

#Method 1 : using for loop add values in each element
#Method 2 : using simple operation

arr = array([1,2,3,4,5])
arrn= arr+5
print(arrn)

[ 6  7  8  9 10]


In [43]:
arr1 = array([1,2,3,4,5])
arr2 = array([10,15,16,23,24])
arr3 = arr1 + arr2                          #Vectorized Operation
print(arr3)

[11 17 19 27 29]


# Mathematical Operation

In [44]:
arr1 = array([10,20,30,40,50])
print('Sin Values: ',sin(arr1))
print('Cos Values: ',cos(arr1))
print('Logarithm: ',log(arr1))

print("max ",max(arr1))
print("sum ",sum(arr1))
print("mean ",mean(arr1))

Sin Values:  [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cos Values:  [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
Logarithm:  [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
max  50
sum  150
mean  30.0


In [45]:
arr1 = array([10,20,30,40,50])
arr2 = arr1                            #Both array stored on same address

print(arr1)
print(arr2)
      
print(id(arr1))
print(id(arr2))

[10 20 30 40 50]
[10 20 30 40 50]
2151981056240
2151981056240


In [46]:
arr1 = array([10,20,30,40,50])
arr2 = arr1.view()                           #array value may be same but but both value would be stored in different address

print(arr1)
print(arr2)
      
print(id(arr1))
print(id(arr2))

[10 20 30 40 50]
[10 20 30 40 50]
2151981056432
2151981057200


In [47]:
#shallow copy

arr1 = array([10,20,30,40,50])
arr2 = arr1.view()

arr1[1] = 7                          # value change for both array stored in different address
print(arr1)
print(arr2)
      
print(id(arr1))
print(id(arr2))

[10  7 30 40 50]
[10  7 30 40 50]
2151981057776
2151981057968


In [48]:
#Deep copy

arr1 = array([10,20,30,40,50])
arr2 = arr1.copy()

arr1[3] = 17                          # value change only for given array

print(arr1)
print(arr2)
      
print(id(arr1))
print(id(arr2))

[10 20 30 17 50]
[10 20 30 40 50]
2151981058352
2151981058448


# Working with Matix in Pyhon

In [49]:
arr1 = array([
              [1,2,3],
              [4,5,6]
             ])

print(arr1)
print("Dimensions    : ",arr1.ndim)                    #Provides dimension of an array and also it ranks the array.
print("Type          : ",arr1.dtype)
print("rows, Column  : ",arr1.shape)                   #rows, columns
print("Size of array : ",arr1.size)                   

[[1 2 3]
 [4 5 6]]
Dimensions    :  2
Type          :  int32
rows, Column  :  (2, 3)
Size of array :  6


In [50]:
arr2 = arr1.flatten()                                 #convert multidimensional array to 1D dimensional array
print(arr2)

[1 2 3 4 5 6]


In [51]:
arr1 = array([
                [1,2,3,7,8,9],
                [4,5,6,3,5,8]
             ])

arr2 = arr1.flatten() 
print("arr2 : 1-D array with 12 values in single array \n",arr2)

arr3 = arr2.reshape(3,4)                # converting 1D array to 2D array
print("\narr3 : 2D array with 3 1-D array having 4 values each \n",arr3)

arr4 = arr2.reshape(2,2,3)              # converting 1D array to 3D array
print("\narr4 : 3-D array with two - 2D array and each 2D array two 1-D array having 3 values each \n",arr4)

arr2 : 1-D array with 12 values in single array 
 [1 2 3 7 8 9 4 5 6 3 5 8]

arr3 : 2D array with 3 1-D array having 4 values each 
 [[1 2 3 7]
 [8 9 4 5]
 [6 3 5 8]]

arr4 : 3-D array with two - 2D array and each 2D array two 1-D array having 3 values each 
 [[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [3 5 8]]]


# Matrices

In [52]:
arr1 = array([
              [1,2,3,9],
              [4,5,17,8]
             ])
print(arr1)

[[ 1  2  3  9]
 [ 4  5 17  8]]


In [53]:
m = matrix(arr1)
print(m)

[[ 1  2  3  9]
 [ 4  5 17  8]]


In [54]:
m = matrix('1 2 3; 9 4 5; 17 6 9')
print(m)

[[ 1  2  3]
 [ 9  4  5]
 [17  6  9]]


In [55]:
print("Diagonal : ",diagonal(m)) #to print diagonal values
print("Max : " ,m.max())
print("Max : " ,m.min())

Diagonal :  [1 4 9]
Max :  17
Max :  1


### Matrix Multiplication

In [56]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')

m3 = m1 * m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
